### ISSUE TITLE
php version & page width

### ISSUE THREAD

**Issue by Fil** [radames/observablehq-viewer#1]
Excellent! I have a hacky PHP script that does something similar (code below for reference). Maybe I should try and converge it to the same API as yours (e.g. url, cells selection, css…). 

I'm noticing a difference in the `width` of the page, where your version has `.mw8 { max-width: 64rem; }`, and mine doesn't add limitations. In the case of [a certain notebook](https://visionscarto.net/obs/?https://observablehq.com/d/44cf25342beb49cb) I want to use the full page width. It can be done from within the notebook by adding a style cell with html`<style>main.mw8 { max-width: 100vw }`. Maybe that's an option worth documenting (with other interesting possibilities, such as alignment).

**Comment by Fil** [comment]
I've made my script more or less compatible with yours: https://gist.github.com/Fil/9d5c8d99e33eee1d4bd5f88c57f8aa7c

**Comment by radames** [comment]
hi @Fil That's a great idea! I'll add a param to enable `fullwidth` what do you think?  disabling the max-width wrapper.

Also It would be great to think a more general preview, where you compose a grid selecting specific cells. Something that would simplify a lot your dashboard example. I'm not sure if it would be simple as calling the preview URL with the notebook URL / cells. 

My initial ideal, I'll propose it at Observablehq forum as a maybe feature, was to create a simple preview mode, disabling their UI. I also saw many folks on the forum, maybe with less time/experience, trying to present cells without the code cells, UI, etc.

**Comment by radames** [comment]
here is a test using your notebook https://observablehq-viewer.glitch.me/d/44cf25342beb49cb?cells=map,chart9&fullwidth=1
